export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_EMPLOYEE_SUCCEEDED = "SET_EMPLOYEE_SUCCEEDED";

export const RESET_EMPLOYEE = "RESET_EMPLOYEE";
export const RESET_EMPLOYEE_SUCCEEDED = "RESET_EMPLOYEE_SUCCEEDED";

export const GET_ALL_EMPLOYEE_REQUESTED = "GET_ALL_EMPLOYEE_REQUESTED";
export const GET_ALL_EMPLOYEE_SUCCEEDED = "GET_ALL_EMPLOYEE_SUCCEEDED";
export const GET_ALL_EMPLOYEE_FAILED = "GET_ALL_EMPLOYEE_FAILED";

export const ADD_EMPLOYEE_REQUESTED = "ADD_EMPLOYEE_REQUESTED";
export const ADD_EMPLOYEE_SUCCEEDED = "ADD_EMPLOYEE_SUCCEEDED";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUESTED = "EDIT_EMPLOYEE_REQUESTED";
export const EDIT_EMPLOYEE_SUCCEEDED = "EDIT_EMPLOYEE_SUCCEEDED";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_REQUESTED = "DELETE_EMPLOYEE_REQUESTED";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

export const GET_TOTAL_EMPLOYEE = "GET_TOTAL_EMPLOYEE";
export const GET_TOTAL_EMPLOYEE_SUCCEEDED = "GET_TOTAL_EMPLOYEE_SUCCEEDED";

export const GET_FORM_EMPLOYEE = "GET_FORM_EMPLOYEE";
export const GET_FORM_EMPLOYEE_SUCCEEDED = "GET_FORM_EMPLOYEE_SUCCEEDED";

export const ADDITIONAL_REQUESTED = "ADDITIONAL_REQUESTED";
export const ADDITIONAL_REQUESTED_SUCCEEDED = "ADDITIONAL_REQUESTED_SUCCEEDED";
